AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  A demo serverless API project, with API gateway, Lambda with AWS Powertools, and DynamoDB.

Globals:
  Function:
    Timeout: 10

Resources:
  BooksFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        GetBooks:
          Type: Api
          Properties:
            Path: /books
            Method: get
        GetBook:
            Type: Api
            Properties:
              Path: /books/{title}
              Method: get
        CreateBook:
          Type: Api
          Properties:
            Path: /books
            Method: post

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
